# WASHINGTON STATE HOME LOANS 2016

## Import the required packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# define data set path
dataFile = "E:/Data Science/SpringBoard DS/Capstone Project 1/Code/Dataset/washington-state-home-mortgage-hdma2016/Washington_State_HDMA-2016.csv"
datatype = {'tract_to_msamd_income': float, 'rate_spread': object, 'population': object, 'minority_population': object, 'number_of_owner_occupied_units': object, 'number_of_1_to_4_family_units': object, 'loan_amount_000s': object, 'hud_median_family_income': object, 'applicant_income_000s': object, 'state_name': object, 'state_abbr': object, 'sequence_number': int, 'respondent_id': object, 'purchaser_type_name': object, 'property_type_name': object, 'preapproval_name': object, 'owner_occupancy_name': object, 'msamd_name': object, 'loan_type_name': object, 'loan_purpose_name': object, 'lien_status_name': object, 'hoepa_status_name': object, 'edit_status_name': object, 'denial_reason_name_3': object, 'denial_reason_name_2': object, 'denial_reason_name_1': object, 'county_name': object, 'co_applicant_sex_name': object, 'co_applicant_race_name_5': object, 'co_applicant_race_name_4': object, 'co_applicant_race_name_3': object, 'co_applicant_race_name_2': object, 'co_applicant_race_name_1': object, 'co_applicant_ethnicity_name': object, 'census_tract_number': float, 'as_of_year': float, 'application_date_indicator': object, 'applicant_sex_name': object, 'applicant_race_name_5': object, 'applicant_race_name_4': object, 'applicant_race_name_3': object, 'applicant_race_name_2': object, 'applicant_race_name_1': object, 'applicant_ethnicity_name': object, 'agency_name': object, 'agency_abbr': object, 'action_taken_name': object}
colnames = ['tract_to_msamd_income', 'rate_spread', 'population', 'minority_population', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units', 'loan_amount_000s', 'hud_median_family_income', 'applicant_income_000s', 'state_name', 'state_abbr', 'sequence_number', 'respondent_id', 'purchaser_type_name', 'property_type_name', 'preapproval_name', 'owner_occupancy_name', 'msamd_name', 'loan_type_name', 'loan_purpose_name', 'lien_status_name', 'hoepa_status_name', 'edit_status_name', 'denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1', 'county_name', 'co_applicant_sex_name', 'co_applicant_race_name_5', 'co_applicant_race_name_4', 'co_applicant_race_name_3', 'co_applicant_race_name_2', 'co_applicant_race_name_1', 'co_applicant_ethnicity_name', 'census_tract_number', 'as_of_year', 'application_date_indicator', 'applicant_sex_name', 'applicant_race_name_5', 'applicant_race_name_4', 'applicant_race_name_3', 'applicant_race_name_2', 'applicant_race_name_1', 'applicant_ethnicity_name', 'agency_name', 'agency_abbr', 'action_taken_name']

In [3]:
# import dataset
WA_HomeLoan_df = pd.read_csv(dataFile, low_memory=False, dtype=datatype, usecols=colnames)

## Inspect Dataset

In [4]:
# print dataset head
pd.set_option('display.max_columns', 50)
WA_HomeLoan_df.head()

,tract_to_msamd_income,rate_spread,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,state_name,state_abbr,sequence_number,respondent_id,purchaser_type_name,property_type_name,preapproval_name,owner_occupancy_name,msamd_name,loan_type_name,loan_purpose_name,lien_status_name,hoepa_status_name,edit_status_name,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,county_name,co_applicant_sex_name,co_applicant_race_name_5,co_applicant_race_name_4,co_applicant_race_name_3,co_applicant_race_name_2,co_applicant_race_name_1,co_applicant_ethnicity_name,census_tract_number,as_of_year,application_date_indicator,applicant_sex_name,applicant_race_name_5,applicant_race_name_4,applicant_race_name_3,applicant_race_name_2,applicant_race_name_1,applicant_ethnicity_name,agency_name,agency_abbr,action_taken_name
0,121.690002,NaN,8381,23.79000092,2175,2660,227,73300,116,Washington,WA,119969,480228,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Male,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...",Not Hispanic or Latino,413.27,2016.0,0,Female,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...",Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
1,83.370003,NaN,4915,23.98999977,1268,1777,240,57900,42,Washington,WA,52605,7257500009,"Life insurance company, credit union, mortgage...",One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,Walla Walla - WA,FHA-insured,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Walla Walla County,No co-applicant,NaN,NaN,NaN,NaN,No co-applicant,No co-applicant,9208.01,2016.0,0,Male,NaN,NaN,NaN,NaN,White,Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
2,91.129997,NaN,5075,11.81999969,1136,1838,241,73300,117,Washington,WA,6210,72-1545376,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Female,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,414.00,2016.0,0,Male,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
3,146.169998,NaN,5032,8.590000153,1525,1820,351,73300,315,Washington,WA,197,4878,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Female,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",405.10,2016.0,0,Male,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",National Credit Union Administration,NCUA,Loan originated
4,162.470001,NaN,5183,10.5,1705,2104,417,78100,114,Washington,WA,32582,32489,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Bremerton, Silverdale - WA",Conventional,Home improvement,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Kitsap County,Male,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,907.00,2016.0,0,Female,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,Federal Deposit Insurance Corporation,FDIC,Loan originated

In [5]:
# Check if all the columns are loaded
WA_HomeLoan_df.shape

(466566, 47)

In [6]:
# print columns to check if column have vaild names
WA_HomeLoan_df.columns

Index([u'tract_to_msamd_income', u'rate_spread', u'population',
       u'minority_population', u'number_of_owner_occupied_units',
       u'number_of_1_to_4_family_units', u'loan_amount_000s',
       u'hud_median_family_income', u'applicant_income_000s', u'state_name',
       u'state_abbr', u'sequence_number', u'respondent_id',
       u'purchaser_type_name', u'property_type_name', u'preapproval_name',
       u'owner_occupancy_name', u'msamd_name', u'loan_type_name',
       u'loan_purpose_name', u'lien_status_name', u'hoepa_status_name',
       u'edit_status_name', u'denial_reason_name_3', u'denial_reason_name_2',
       u'denial_reason_name_1', u'county_name', u'co_applicant_sex_name',
       u'co_applicant_race_name_5', u'co_applicant_race_name_4',
       u'co_applicant_race_name_3', u'co_applicant_race_name_2',
       u'co_applicant_race_name_1', u'co_applicant_ethnicity_name',
       u'census_tract_number', u'as_of_year', u'application_date_indicator',
       u'applicant_sex_name', u'applicant_race_name_5',
       u'applicant_race_name_4', u'applicant_race_name_3',
       u'applicant_race_name_2', u'applicant_race_name_1',
       u'applicant_ethnicity_name', u'agency_name', u'agency_abbr',
       u'action_taken_name'],
      dtype='object')

Columns names doesn't contain special characters or spaces

In [7]:
# inspect dataset info
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 47 columns):
tract_to_msamd_income             465951 non-null float64
rate_spread                       8638 non-null object
population                        465956 non-null object
minority_population               465956 non-null object
number_of_owner_occupied_units    465944 non-null object
number_of_1_to_4_family_units     465955 non-null object
loan_amount_000s                  466566 non-null object
hud_median_family_income          465960 non-null object
applicant_income_000s             404533 non-null object
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_3              1246 non-null object
denial_reason_name_2              6746 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null object
co_applicant_race_name_5          14 non-null object
co_applicant_race_name_4          21 non-null object
co_applicant_race_name_3          105 non-null object
co_applicant_race_name_2          1862 non-null object
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null object
applicant_sex_name                466566 non-null object
applicant_race_name_5             46 non-null object
applicant_race_name_4             68 non-null object
applicant_race_name_3             297 non-null object
applicant_race_name_2             4478 non-null object
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: float64(3), int32(1), object(43)
memory usage: 165.5+ MB

- Some columns contain very few non-null values
- All the columns have object data type
- Some columns missing (NaN) value

## Drop Columns

In [8]:
#drop column with few data values
drop_columns = ['denial_reason_name_3', 'denial_reason_name_2', 'co_applicant_race_name_5', 'co_applicant_race_name_4', 'co_applicant_race_name_3', 'co_applicant_race_name_2', 'applicant_race_name_5', 'applicant_race_name_4', 'applicant_race_name_3', 'applicant_race_name_2']
WA_HomeLoan_df.drop(columns=drop_columns, inplace=True, axis='columns')

In [9]:
# Verify if the columns are dropped
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 37 columns):
tract_to_msamd_income             465951 non-null float64
rate_spread                       8638 non-null object
population                        465956 non-null object
minority_population               465956 non-null object
number_of_owner_occupied_units    465944 non-null object
number_of_1_to_4_family_units     465955 non-null object
loan_amount_000s                  466566 non-null object
hud_median_family_income          465960 non-null object
applicant_income_000s             404533 non-null object
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null object
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null object
applicant_sex_name                466566 non-null object
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: float64(3), int32(1), object(33)
memory usage: 129.9+ MB

## Column Data Types

In [10]:
# change column data types
WA_HomeLoan_df.rate_spread = pd.to_numeric(WA_HomeLoan_df.rate_spread, errors='coerce')
WA_HomeLoan_df.population = pd.to_numeric(WA_HomeLoan_df.population, errors='coerce')
WA_HomeLoan_df.minority_population = pd.to_numeric(WA_HomeLoan_df.minority_population, errors='coerce')
WA_HomeLoan_df.number_of_owner_occupied_units = pd.to_numeric(WA_HomeLoan_df.number_of_owner_occupied_units, errors='coerce')
WA_HomeLoan_df.number_of_1_to_4_family_units = pd.to_numeric(WA_HomeLoan_df.number_of_1_to_4_family_units, errors='coerce')
WA_HomeLoan_df.loan_amount_000s = pd.to_numeric(WA_HomeLoan_df.loan_amount_000s, errors='coerce')
WA_HomeLoan_df.hud_median_family_income = pd.to_numeric(WA_HomeLoan_df.hud_median_family_income, errors='coerce')
WA_HomeLoan_df.applicant_income_000s = pd.to_numeric(WA_HomeLoan_df.applicant_income_000s, errors='coerce')
WA_HomeLoan_df.co_applicant_sex_name = WA_HomeLoan_df.co_applicant_sex_name.astype('category')
WA_HomeLoan_df.application_date_indicator = WA_HomeLoan_df.application_date_indicator.astype('int')
WA_HomeLoan_df.applicant_sex_name = WA_HomeLoan_df.applicant_sex_name.astype('category')

In [11]:
# Inspect dataset info
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 37 columns):
tract_to_msamd_income             465951 non-null float64
rate_spread                       8638 non-null float64
population                        465956 non-null float64
minority_population               465956 non-null float64
number_of_owner_occupied_units    465944 non-null float64
number_of_1_to_4_family_units     465955 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          465960 non-null float64
applicant_income_000s             404533 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null category
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null int32
applicant_sex_name                466566 non-null category
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: category(2), float64(10), int32(2), int64(1), object(22)
memory usage: 121.9+ MB

## Missing Data

Numeric columns with missing data (NaN value) are substituted with median value

In [12]:
# Substitute numerica columns with missing data with median vlues
WA_HomeLoan_df.tract_to_msamd_income.fillna(WA_HomeLoan_df.tract_to_msamd_income.median(), inplace=True)
WA_HomeLoan_df.rate_spread.fillna(WA_HomeLoan_df.rate_spread.median(), inplace=True)
WA_HomeLoan_df.population.fillna(WA_HomeLoan_df.population.median(), inplace=True)
WA_HomeLoan_df.minority_population.fillna(WA_HomeLoan_df.minority_population.median(), inplace=True)
WA_HomeLoan_df.number_of_owner_occupied_units.fillna(WA_HomeLoan_df.number_of_owner_occupied_units.median(), inplace=True)
WA_HomeLoan_df.number_of_1_to_4_family_units.fillna(WA_HomeLoan_df.number_of_1_to_4_family_units.median(), inplace=True)
WA_HomeLoan_df.loan_amount_000s.fillna(WA_HomeLoan_df.loan_amount_000s.median(), inplace=True)
WA_HomeLoan_df.hud_median_family_income.fillna(WA_HomeLoan_df.hud_median_family_income.median(), inplace=True)
WA_HomeLoan_df.applicant_income_000s.fillna(WA_HomeLoan_df.applicant_income_000s.median(), inplace=True)
WA_HomeLoan_df.head(5)

,tract_to_msamd_income,rate_spread,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,state_name,state_abbr,sequence_number,respondent_id,purchaser_type_name,property_type_name,preapproval_name,owner_occupancy_name,msamd_name,loan_type_name,loan_purpose_name,lien_status_name,hoepa_status_name,edit_status_name,denial_reason_name_1,county_name,co_applicant_sex_name,co_applicant_race_name_1,co_applicant_ethnicity_name,census_tract_number,as_of_year,application_date_indicator,applicant_sex_name,applicant_race_name_1,applicant_ethnicity_name,agency_name,agency_abbr,action_taken_name
0,121.690002,1.72,8381.0,23.790001,2175.0,2660.0,227,73300.0,116.0,Washington,WA,119969,480228,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,Clark County,Male,"Information not provided by applicant in mail,...",Not Hispanic or Latino,413.27,2016.0,0,Female,"Information not provided by applicant in mail,...",Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
1,83.370003,1.72,4915.0,23.990000,1268.0,1777.0,240,57900.0,42.0,Washington,WA,52605,7257500009,"Life insurance company, credit union, mortgage...",One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,Walla Walla - WA,FHA-insured,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,NaN,Walla Walla County,No co-applicant,No co-applicant,No co-applicant,9208.01,2016.0,0,Male,White,Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
2,91.129997,1.72,5075.0,11.820000,1136.0,1838.0,241,73300.0,117.0,Washington,WA,6210,72-1545376,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,Clark County,Female,White,Not Hispanic or Latino,414.00,2016.0,0,Male,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
3,146.169998,1.72,5032.0,8.590000,1525.0,1820.0,351,73300.0,315.0,Washington,WA,197,4878,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,Clark County,Female,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",405.10,2016.0,0,Male,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",National Credit Union Administration,NCUA,Loan originated
4,162.470001,1.72,5183.0,10.500000,1705.0,2104.0,417,78100.0,114.0,Washington,WA,32582,32489,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Bremerton, Silverdale - WA",Conventional,Home improvement,Secured by a first lien,Not a HOEPA loan,NaN,NaN,Kitsap County,Male,White,Not Hispanic or Latino,907.00,2016.0,0,Female,White,Not Hispanic or Latino,Federal Deposit Insurance Corporation,FDIC,Loan originated

In [13]:
# inspect dataset info
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 37 columns):
tract_to_msamd_income             466566 non-null float64
rate_spread                       466566 non-null float64
population                        466566 non-null float64
minority_population               466566 non-null float64
number_of_owner_occupied_units    466566 non-null float64
number_of_1_to_4_family_units     466566 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          466566 non-null float64
applicant_income_000s             466566 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null category
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null int32
applicant_sex_name                466566 non-null category
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: category(2), float64(10), int32(2), int64(1), object(22)
memory usage: 121.9+ MB

## Summary of Statistics

In [14]:
#Summary of statistics
WA_HomeLoan_df.describe()

,tract_to_msamd_income,rate_spread,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,sequence_number,census_tract_number,as_of_year,application_date_indicator
count,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,4.665660e+05,465960.000000,466566.0,466566.000000
mean,106.903025,1.727406,5288.068477,24.760225,1389.019706,1822.021866,298.260936,76792.606191,109.795789,1.126340e+05,1395.489104,2016.0,0.207285
std,29.261241,0.160748,1664.266258,15.205345,506.419344,681.592415,760.741532,12951.245719,116.786197,2.020866e+05,2950.970895,0.0,0.609576
min,14.050000,1.500000,5.000000,2.040000,10.000000,10.000000,1.000000,48700.000000,1.000000,1.000000e+00,1.000000,2016.0,0.000000
25%,87.279999,1.720000,4124.000000,13.220000,1032.000000,1397.000000,172.000000,65800.000000,64.000000,5.121000e+03,117.010000,2016.0,0.000000
50%,104.529999,1.720000,5173.000000,20.750000,1359.000000,1734.000000,248.000000,73300.000000,89.000000,2.647200e+04,323.220000,2016.0,0.000000
75%,123.709999,1.720000,6342.000000,32.220001,1705.000000,2171.000000,350.000000,90300.000000,125.000000,1.095258e+05,702.030000,2016.0,0.000000
max,257.140015,13.660000,13025.000000,94.790001,2997.000000,5893.000000,99999.000000,90300.000000,9999.000000,1.241780e+06,9901.000000,2016.0,2.000000

## Outliers

In [15]:
#functions for removing outliers
def removeOutliers(columnName):
    q25 = columnName.quantile(0.25)
    q75 = columnName.quantile(0.75)
    iqr =  q75 - q25
    cutoff = iqr*1.5
    lower = q25 - cutoff
    higher = q75 + cutoff
    columnName.mask(columnName < lower, other = lower, inplace=True)
    columnName.mask(columnName > higher, other = higher, inplace=True)

In [16]:
# Remove outliers
removeOutliers(WA_HomeLoan_df.tract_to_msamd_income)
removeOutliers(WA_HomeLoan_df.rate_spread)
removeOutliers(WA_HomeLoan_df.population)
removeOutliers(WA_HomeLoan_df.minority_population)
removeOutliers(WA_HomeLoan_df.number_of_owner_occupied_units)
removeOutliers(WA_HomeLoan_df.number_of_1_to_4_family_units)
removeOutliers(WA_HomeLoan_df.loan_amount_000s)
removeOutliers(WA_HomeLoan_df.hud_median_family_income)
removeOutliers(WA_HomeLoan_df.applicant_income_000s)

In [17]:
# Summary of statistics
WA_HomeLoan_df.describe()

,tract_to_msamd_income,rate_spread,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,sequence_number,census_tract_number,as_of_year,application_date_indicator
count,466566.000000,4.665660e+05,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,466566.000000,4.665660e+05,465960.000000,466566.0,466566.000000
mean,106.577297,1.720000e+00,5276.670895,24.362200,1387.722648,1805.265677,270.850793,76792.606191,99.807230,1.126340e+05,1395.489104,2016.0,0.207285
std,28.139842,1.846214e-11,1628.245549,13.968457,502.703472,617.759192,141.464202,12951.245719,50.862448,2.020866e+05,2950.970895,0.0,0.609576
min,32.634998,1.720000e+00,797.000000,2.040000,22.500000,236.000000,1.000000,48700.000000,1.000000,1.000000e+00,1.000000,2016.0,0.000000
25%,87.279999,1.720000e+00,4124.000000,13.220000,1032.000000,1397.000000,172.000000,65800.000000,64.000000,5.121000e+03,117.010000,2016.0,0.000000
50%,104.529999,1.720000e+00,5173.000000,20.750000,1359.000000,1734.000000,248.000000,73300.000000,89.000000,2.647200e+04,323.220000,2016.0,0.000000
75%,123.709999,1.720000e+00,6342.000000,32.220001,1705.000000,2171.000000,350.000000,90300.000000,125.000000,1.095258e+05,702.030000,2016.0,0.000000
max,178.355000,1.720000e+00,9669.000000,60.720003,2714.500000,3332.000000,617.000000,90300.000000,216.500000,1.241780e+06,9901.000000,2016.0,2.000000

## Duplicate Rows

In [18]:
#drop duplicates
WA_HomeLoan_df.drop_duplicates(inplace=True)

In [19]:
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 466566 entries, 0 to 466565
Data columns (total 37 columns):
tract_to_msamd_income             466566 non-null float64
rate_spread                       466566 non-null float64
population                        466566 non-null float64
minority_population               466566 non-null float64
number_of_owner_occupied_units    466566 non-null float64
number_of_1_to_4_family_units     466566 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          466566 non-null float64
applicant_income_000s             466566 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null category
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null int32
applicant_sex_name                466566 non-null category
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: category(2), float64(10), int32(2), int64(1), object(22)
memory usage: 125.5+ MB