# WASHINGTON STATE HOME LOANS 2016

## Import the required packages

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# define data set path
dataFile = "E:/Data Science/SpringBoard DS/Capstone Project 1/Code/Dataset/washington-state-home-mortgage-hdma2016/Washington_State_HDMA-2016.csv"
#datatype = {'tract_to_msamd_income': float, 'rate_spread': object, 'population': object, 'minority_population': object, 'number_of_owner_occupied_units': object, 'number_of_1_to_4_family_units': object, 'loan_amount_000s': object, 'hud_median_family_income': object, 'applicant_income_000s': object, 'state_name': object, 'state_abbr': object, 'sequence_number': int, 'respondent_id': object, 'purchaser_type_name': object, 'property_type_name': object, 'preapproval_name': object, 'owner_occupancy_name': object, 'msamd_name': object, 'loan_type_name': object, 'loan_purpose_name': object, 'lien_status_name': object, 'hoepa_status_name': object, 'edit_status_name': object, 'denial_reason_name_3': object, 'denial_reason_name_2': object, 'denial_reason_name_1': object, 'county_name': object, 'co_applicant_sex_name': object, 'co_applicant_race_name_5': object, 'co_applicant_race_name_4': object, 'co_applicant_race_name_3': object, 'co_applicant_race_name_2': object, 'co_applicant_race_name_1': object, 'co_applicant_ethnicity_name': object, 'census_tract_number': float, 'as_of_year': float, 'application_date_indicator': object, 'applicant_sex_name': object, 'applicant_race_name_5': object, 'applicant_race_name_4': object, 'applicant_race_name_3': object, 'applicant_race_name_2': object, 'applicant_race_name_1': object, 'applicant_ethnicity_name': object, 'agency_name': object, 'agency_abbr': object, 'action_taken_name': object}
#colnames = ['tract_to_msamd_income', 'rate_spread', 'population', 'minority_population', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units', 'loan_amount_000s', 'hud_median_family_income', 'applicant_income_000s', 'state_name', 'state_abbr', 'sequence_number', 'respondent_id', 'purchaser_type_name', 'property_type_name', 'preapproval_name', 'owner_occupancy_name', 'msamd_name', 'loan_type_name', 'loan_purpose_name', 'lien_status_name', 'hoepa_status_name', 'edit_status_name', 'denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1', 'county_name', 'co_applicant_sex_name', 'co_applicant_race_name_5', 'co_applicant_race_name_4', 'co_applicant_race_name_3', 'co_applicant_race_name_2', 'co_applicant_race_name_1', 'co_applicant_ethnicity_name', 'census_tract_number', 'as_of_year', 'application_date_indicator', 'applicant_sex_name', 'applicant_race_name_5', 'applicant_race_name_4', 'applicant_race_name_3', 'applicant_race_name_2', 'applicant_race_name_1', 'applicant_ethnicity_name', 'agency_name', 'agency_abbr', 'action_taken_name']

In [3]:
# import dataset
#WA_HomeLoan_df = pd.read_csv(dataFile, low_memory=False, dtype=datatype, usecols=colnames)

In [3]:
WA_HomeLoan_df = pd.read_csv(dataFile, low_memory=True)

C:\Users\Priyanka\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (23,24,25,28,29,30,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Inspect Dataset

In [4]:
# print dataset head

pd.set_option('display.max_columns', 50)
WA_HomeLoan_df.head()

,tract_to_msamd_income,rate_spread,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,state_name,state_abbr,sequence_number,respondent_id,purchaser_type_name,property_type_name,preapproval_name,owner_occupancy_name,msamd_name,loan_type_name,loan_purpose_name,lien_status_name,hoepa_status_name,edit_status_name,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,county_name,co_applicant_sex_name,co_applicant_race_name_5,co_applicant_race_name_4,co_applicant_race_name_3,co_applicant_race_name_2,co_applicant_race_name_1,co_applicant_ethnicity_name,census_tract_number,as_of_year,application_date_indicator,applicant_sex_name,applicant_race_name_5,applicant_race_name_4,applicant_race_name_3,applicant_race_name_2,applicant_race_name_1,applicant_ethnicity_name,agency_name,agency_abbr,action_taken_name
0,121.690002,NaN,8381.0,23.790001,2175.0,2660.0,227,73300.0,116.0,Washington,WA,119969,480228,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Male,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...",Not Hispanic or Latino,413.27,2016,0,Female,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...",Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
1,83.370003,NaN,4915.0,23.990000,1268.0,1777.0,240,57900.0,42.0,Washington,WA,52605,7257500009,"Life insurance company, credit union, mortgage...",One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,Walla Walla - WA,FHA-insured,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Walla Walla County,No co-applicant,NaN,NaN,NaN,NaN,No co-applicant,No co-applicant,9208.01,2016,0,Male,NaN,NaN,NaN,NaN,White,Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
2,91.129997,NaN,5075.0,11.820000,1136.0,1838.0,241,73300.0,117.0,Washington,WA,6210,72-1545376,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Female,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,414.00,2016,0,Male,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
3,146.169998,NaN,5032.0,8.590000,1525.0,1820.0,351,73300.0,315.0,Washington,WA,197,4878,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Clark County,Female,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",405.10,2016,0,Male,NaN,NaN,NaN,NaN,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",National Credit Union Administration,NCUA,Loan originated
4,162.470001,NaN,5183.0,10.500000,1705.0,2104.0,417,78100.0,114.0,Washington,WA,32582,32489,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Bremerton, Silverdale - WA",Conventional,Home improvement,Secured by a first lien,Not a HOEPA loan,NaN,NaN,NaN,NaN,Kitsap County,Male,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,907.00,2016,0,Female,NaN,NaN,NaN,NaN,White,Not Hispanic or Latino,Federal Deposit Insurance Corporation,FDIC,Loan originated

In [6]:
WA_HomeLoan_df.dtypes

tract_to_msamd_income             float64
rate_spread                       float64
population                        float64
minority_population               float64
number_of_owner_occupied_units    float64
number_of_1_to_4_family_units     float64
loan_amount_000s                    int64
hud_median_family_income          float64
applicant_income_000s             float64
state_name                         object
state_abbr                         object
sequence_number                     int64
respondent_id                      object
purchaser_type_name                object
property_type_name                 object
preapproval_name                   object
owner_occupancy_name               object
msamd_name                         object
loan_type_name                     object
loan_purpose_name                  object
lien_status_name                   object
hoepa_status_name                  object
edit_status_name                   object
denial_reason_name_3               object
denial_reason_name_2               object
denial_reason_name_1               object
county_name                        object
co_applicant_sex_name              object
co_applicant_race_name_5           object
co_applicant_race_name_4           object
co_applicant_race_name_3           object
co_applicant_race_name_2           object
co_applicant_race_name_1           object
co_applicant_ethnicity_name        object
census_tract_number               float64
as_of_year                          int64
application_date_indicator          int64
applicant_sex_name                 object
applicant_race_name_5              object
applicant_race_name_4              object
applicant_race_name_3              object
applicant_race_name_2              object
applicant_race_name_1              object
applicant_ethnicity_name           object
agency_name                        object
agency_abbr                        object
action_taken_name                  object
dtype: object

In [7]:
# Check if all the columns are loaded
WA_HomeLoan_df.shape

(466566, 47)

In [8]:
# print columns to check if column have vaild names
WA_HomeLoan_df.columns

Index([u'tract_to_msamd_income', u'rate_spread', u'population',
       u'minority_population', u'number_of_owner_occupied_units',
       u'number_of_1_to_4_family_units', u'loan_amount_000s',
       u'hud_median_family_income', u'applicant_income_000s', u'state_name',
       u'state_abbr', u'sequence_number', u'respondent_id',
       u'purchaser_type_name', u'property_type_name', u'preapproval_name',
       u'owner_occupancy_name', u'msamd_name', u'loan_type_name',
       u'loan_purpose_name', u'lien_status_name', u'hoepa_status_name',
       u'edit_status_name', u'denial_reason_name_3', u'denial_reason_name_2',
       u'denial_reason_name_1', u'county_name', u'co_applicant_sex_name',
       u'co_applicant_race_name_5', u'co_applicant_race_name_4',
       u'co_applicant_race_name_3', u'co_applicant_race_name_2',
       u'co_applicant_race_name_1', u'co_applicant_ethnicity_name',
       u'census_tract_number', u'as_of_year', u'application_date_indicator',
       u'applicant_sex_name', u'applicant_race_name_5',
       u'applicant_race_name_4', u'applicant_race_name_3',
       u'applicant_race_name_2', u'applicant_race_name_1',
       u'applicant_ethnicity_name', u'agency_name', u'agency_abbr',
       u'action_taken_name'],
      dtype='object')

Columns names doesn't contain special characters or spaces

In [17]:
#Inspect columns
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 35 columns):
tract_to_msamd_income             465951 non-null float64
population                        465956 non-null float64
minority_population               465956 non-null float64
number_of_owner_occupied_units    465944 non-null float64
number_of_1_to_4_family_units     465955 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          465960 non-null float64
applicant_income_000s             404533 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int64
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null category
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null int64
application_date_indicator        466566 non-null int64
applicant_sex_name                466566 non-null category
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: category(2), float64(8), int64(4), object(21)
memory usage: 118.4+ MB

- Some columns contain very few non-null values
- denial_reason_name_3              1246 non-null object
- denial_reason_name_2              6746 non-null object
- co_applicant_race_name_5          14 non-null object
- co_applicant_race_name_4          21 non-null object
- co_applicant_race_name_3          105 non-null object
- co_applicant_race_name_2          1862 non-null object
- applicant_race_name_5             46 non-null object
- applicant_race_name_4             68 non-null object
- applicant_race_name_3             297 non-null object
- applicant_race_name_2             4478 non-null object
- Some columns missing (NaN) value

## Drop Columns

In [5]:
#drop column with less than 20% data values
drop_columns = ['rate_spread','edit_status_name', 'denial_reason_name_3', 'denial_reason_name_2', 'co_applicant_race_name_5', 'co_applicant_race_name_4', 'co_applicant_race_name_3', 'co_applicant_race_name_2', 'applicant_race_name_5', 'applicant_race_name_4', 'applicant_race_name_3', 'applicant_race_name_2']
WA_HomeLoan_df.drop(columns=drop_columns, inplace=True, axis='columns')

In [6]:
# Verify if the columns are dropped
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466566 entries, 0 to 466565
Data columns (total 35 columns):
tract_to_msamd_income             465951 non-null float64
population                        465956 non-null float64
minority_population               465956 non-null float64
number_of_owner_occupied_units    465944 non-null float64
number_of_1_to_4_family_units     465955 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          465960 non-null float64
applicant_income_000s             404533 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int64
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null object
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null int64
application_date_indicator        466566 non-null int64
applicant_sex_name                466566 non-null object
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: float64(8), int64(4), object(23)
memory usage: 124.6+ MB

## Column Data Types

In [7]:
# change column data types
WA_HomeLoan_df.co_applicant_sex_name = WA_HomeLoan_df.co_applicant_sex_name.astype('category')
WA_HomeLoan_df.applicant_sex_name = WA_HomeLoan_df.applicant_sex_name.astype('category')

In [8]:
# Inspect dataset info
WA_HomeLoan_df.dtypes

tract_to_msamd_income              float64
population                         float64
minority_population                float64
number_of_owner_occupied_units     float64
number_of_1_to_4_family_units      float64
loan_amount_000s                     int64
hud_median_family_income           float64
applicant_income_000s              float64
state_name                          object
state_abbr                          object
sequence_number                      int64
respondent_id                       object
purchaser_type_name                 object
property_type_name                  object
preapproval_name                    object
owner_occupancy_name                object
msamd_name                          object
loan_type_name                      object
loan_purpose_name                   object
lien_status_name                    object
hoepa_status_name                   object
denial_reason_name_1                object
county_name                         object
co_applicant_sex_name             category
co_applicant_race_name_1            object
co_applicant_ethnicity_name         object
census_tract_number                float64
as_of_year                           int64
application_date_indicator           int64
applicant_sex_name                category
applicant_race_name_1               object
applicant_ethnicity_name            object
agency_name                         object
agency_abbr                         object
action_taken_name                   object
dtype: object

## Missing Data

Numeric columns with missing data (NaN value) are substituted with median value

# Substitute numerica columns with missing data with median vlues
WA_HomeLoan_df.tract_to_msamd_income.fillna(WA_HomeLoan_df.tract_to_msamd_income.median(), inplace=True)
WA_HomeLoan_df.rate_spread.fillna(WA_HomeLoan_df.rate_spread.median(), inplace=True)
WA_HomeLoan_df.population.fillna(WA_HomeLoan_df.population.median(), inplace=True)
WA_HomeLoan_df.minority_population.fillna(WA_HomeLoan_df.minority_population.median(), inplace=True)
WA_HomeLoan_df.number_of_owner_occupied_units.fillna(WA_HomeLoan_df.number_of_owner_occupied_units.median(), inplace=True)
WA_HomeLoan_df.number_of_1_to_4_family_units.fillna(WA_HomeLoan_df.number_of_1_to_4_family_units.median(), inplace=True)
WA_HomeLoan_df.loan_amount_000s.fillna(WA_HomeLoan_df.loan_amount_000s.median(), inplace=True)
WA_HomeLoan_df.hud_median_family_income.fillna(WA_HomeLoan_df.hud_median_family_income.median(), inplace=True)
WA_HomeLoan_df.applicant_income_000s.fillna(WA_HomeLoan_df.applicant_income_000s.median(), inplace=True)
WA_HomeLoan_df.head(5)

In [9]:
#WA_HomeLoan_df.population.value_counts()
#WA_HL_Tract = WA_HomeLoan_df[WA_HomeLoan_df.tract_to_msamd_income.isna() & WA_HomeLoan_df.population.isna() & WA_HomeLoan_df.minority_population.isna() & WA_HomeLoan_df.number_of_owner_occupied_units.isna() & WA_HomeLoan_df.number_of_1_to_4_family_units.isna]
#WA_HL_Tract.head(600)
WA_HomeLoan_df.dropna(axis=0, subset=['tract_to_msamd_income'], inplace=True)

In [10]:
#WA_HomeLoan_df.number_of_owner_occupied_units.fillna(WA_HomeLoan_df.number_of_owner_occupied_units.median(), inplace=True)
WA_HomeLoan_df.applicant_income_000s.fillna(WA_HomeLoan_df.applicant_income_000s.median(), inplace=True)

In [11]:
WA_HomeLoan_df.head(5)

,tract_to_msamd_income,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,state_name,state_abbr,sequence_number,respondent_id,purchaser_type_name,property_type_name,preapproval_name,owner_occupancy_name,msamd_name,loan_type_name,loan_purpose_name,lien_status_name,hoepa_status_name,denial_reason_name_1,county_name,co_applicant_sex_name,co_applicant_race_name_1,co_applicant_ethnicity_name,census_tract_number,as_of_year,application_date_indicator,applicant_sex_name,applicant_race_name_1,applicant_ethnicity_name,agency_name,agency_abbr,action_taken_name
0,121.690002,8381.0,23.790001,2175.0,2660.0,227,73300.0,116.0,Washington,WA,119969,480228,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,Clark County,Male,"Information not provided by applicant in mail,...",Not Hispanic or Latino,413.27,2016,0,Female,"Information not provided by applicant in mail,...",Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
1,83.370003,4915.0,23.990000,1268.0,1777.0,240,57900.0,42.0,Washington,WA,52605,7257500009,"Life insurance company, credit union, mortgage...",One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,Walla Walla - WA,FHA-insured,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,Walla Walla County,No co-applicant,No co-applicant,No co-applicant,9208.01,2016,0,Male,White,Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
2,91.129997,5075.0,11.820000,1136.0,1838.0,241,73300.0,117.0,Washington,WA,6210,72-1545376,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,Clark County,Female,White,Not Hispanic or Latino,414.00,2016,0,Male,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
3,146.169998,5032.0,8.590000,1525.0,1820.0,351,73300.0,315.0,Washington,WA,197,4878,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Portland, Vancouver, Hillsboro - OR, WA",Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,Clark County,Female,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",405.10,2016,0,Male,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",National Credit Union Administration,NCUA,Loan originated
4,162.470001,5183.0,10.500000,1705.0,2104.0,417,78100.0,114.0,Washington,WA,32582,32489,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,"Bremerton, Silverdale - WA",Conventional,Home improvement,Secured by a first lien,Not a HOEPA loan,NaN,Kitsap County,Male,White,Not Hispanic or Latino,907.00,2016,0,Female,White,Not Hispanic or Latino,Federal Deposit Insurance Corporation,FDIC,Loan originated

In [12]:
#dropcolumns = ['tract_to_msamd_income', 'population', 'minority_population', 'number_of_owner_occupied_units', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units', 'loan_amount_000s', 'hud_median_family_income', 'applicant_income_000s', 'msamd_name', 'county_name']
#WA_HomeLoan_df.dropna(axis=0, subset=dropcolumns, inplace=True)
#WA_HomeLoan_df[WA_HomeLoan_df.msamd_name.isna()]['census_tract_number']
census_tract = WA_HomeLoan_df.groupby(by=['msamd_name','census_tract_number'])['tract_to_msamd_income', 'population'].count()
census_tract.head(5)

                                     tract_to_msamd_income  population
msamd_name      census_tract_number
Bellingham - WA 1.00                                   529         529
                2.00                                   566         566
                3.00                                   287         287
                4.00                                   399         399
                5.01                                   283         283

In [13]:
census_tract.reset_index(inplace=True)

In [14]:
census_tract.head(5)

        msamd_name  census_tract_number  tract_to_msamd_income  population
0  Bellingham - WA                 1.00                    529         529
1  Bellingham - WA                 2.00                    566         566
2  Bellingham - WA                 3.00                    287         287
3  Bellingham - WA                 4.00                    399         399
4  Bellingham - WA                 5.01                    283         283

In [15]:
census_tract.drop(columns=['tract_to_msamd_income', 'population'], inplace=True, axis='columns')

In [36]:
census_tract.head(100)

                    msamd_name  census_tract_number
0              Bellingham - WA                 1.00
1              Bellingham - WA                 2.00
2              Bellingham - WA                 3.00
3              Bellingham - WA                 4.00
4              Bellingham - WA                 5.01
5              Bellingham - WA                 5.02
6              Bellingham - WA                 6.00
7              Bellingham - WA                 7.00
8              Bellingham - WA                 8.03
9              Bellingham - WA                 8.04
10             Bellingham - WA                 8.05
11             Bellingham - WA                 8.06
12             Bellingham - WA                 9.01
13             Bellingham - WA                 9.02
14             Bellingham - WA                10.00
15             Bellingham - WA                11.00
16             Bellingham - WA                12.01
17             Bellingham - WA                12.02
18             Bellingham - WA               101.00
19             Bellingham - WA               102.00
20             Bellingham - WA               103.01
21             Bellingham - WA               103.02
22             Bellingham - WA               103.03
23             Bellingham - WA               104.01
24             Bellingham - WA               104.03
25             Bellingham - WA               104.04
26             Bellingham - WA               105.01
27             Bellingham - WA               105.02
28             Bellingham - WA               106.00
29             Bellingham - WA               107.01
..                         ...                  ...
70  Bremerton, Silverdale - WA               920.00
71  Bremerton, Silverdale - WA               921.00
72  Bremerton, Silverdale - WA               922.00
73  Bremerton, Silverdale - WA               923.00
74  Bremerton, Silverdale - WA               924.00
75  Bremerton, Silverdale - WA               925.00
76  Bremerton, Silverdale - WA               926.00
77  Bremerton, Silverdale - WA               927.01
78  Bremerton, Silverdale - WA               927.04
79  Bremerton, Silverdale - WA               928.01
80  Bremerton, Silverdale - WA               928.02
81  Bremerton, Silverdale - WA               928.03
82  Bremerton, Silverdale - WA               929.01
83  Bremerton, Silverdale - WA               929.02
84  Bremerton, Silverdale - WA              9400.00
85  Bremerton, Silverdale - WA              9401.00
86    Kennewick, Richland - WA               101.00
87    Kennewick, Richland - WA               102.01
88    Kennewick, Richland - WA               102.02
89    Kennewick, Richland - WA               103.00
90    Kennewick, Richland - WA               104.00
91    Kennewick, Richland - WA               105.00
92    Kennewick, Richland - WA               106.00
93    Kennewick, Richland - WA               107.01
94    Kennewick, Richland - WA               107.03
95    Kennewick, Richland - WA               107.05
96    Kennewick, Richland - WA               107.07
97    Kennewick, Richland - WA               107.08
98    Kennewick, Richland - WA               108.03
99    Kennewick, Richland - WA               108.05

[100 rows x 2 columns]

In [47]:
#final = WA_HomeLoan_df.merge(census_tract, on='census_tract_number', how='inner')
#final = WA_HomeLoan_df.join(census_tract, on='census_tract_number', how='left')
#final = pd.merge(WA_HomeLoan_df, census_tract, left_on='census_tract_number', right_on='census_tract_number')
#final = WA_HomeLoan_df.merge(census_tract)

In [17]:
#final.head()

In [50]:
WA_HomeLoan_df.shape

(465951, 35)

In [49]:
final.shape

(428278, 35)

In [62]:
msamd_null = WA_HomeLoan_df[WA_HomeLoan_df.msamd_name.isna()]
msamd_null.head()

,tract_to_msamd_income,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,state_name,state_abbr,sequence_number,respondent_id,purchaser_type_name,property_type_name,preapproval_name,owner_occupancy_name,msamd_name,loan_type_name,loan_purpose_name,lien_status_name,hoepa_status_name,denial_reason_name_1,county_name,co_applicant_sex_name,co_applicant_race_name_1,co_applicant_ethnicity_name,census_tract_number,as_of_year,application_date_indicator,applicant_sex_name,applicant_race_name_1,applicant_ethnicity_name,agency_name,agency_abbr,action_taken_name
87,148.710007,4400.0,8.520000,1850.0,2304.0,361,55600.0,257.0,Washington,WA,411380,7197000003,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Not owner-occupied as a principal dwelling,NaN,Conventional,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,Island County,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",9714.0,2016,0,"Information not provided by applicant in mail,...","Information not provided by applicant in mail,...","Information not provided by applicant in mail,...",Department of Housing and Urban Development,HUD,Loan originated
91,110.930000,6131.0,31.690001,1606.0,2441.0,290,55600.0,72.0,Washington,WA,4507,471809999,Loan was not originated or was not sold in cal...,One-to-four family dwelling (other than manufa...,Preapproval was not requested,Owner-occupied as a principal dwelling,NaN,VA-guaranteed,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,Island County,Female,White,Not Hispanic or Latino,9704.0,2016,0,Male,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated
101,111.809998,6773.0,8.890000,2120.0,2677.0,417,55600.0,420.0,Washington,WA,308505,451965,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,NaN,Conventional,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,Grays Harbor County,No co-applicant,No co-applicant,No co-applicant,4.0,2016,0,Male,White,Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
106,74.540001,2806.0,12.870000,665.0,1136.0,161,55600.0,33.0,Washington,WA,377164,451965,Freddie Mac (FHLMC),One-to-four family dwelling (other than manufa...,Not applicable,Not owner-occupied as a principal dwelling,NaN,Conventional,Home purchase,Secured by a first lien,Not a HOEPA loan,NaN,Clallam County,No co-applicant,No co-applicant,No co-applicant,9.0,2016,0,Female,Asian,Not Hispanic or Latino,Consumer Financial Protection Bureau,CFPB,Loan originated
116,94.029999,3303.0,10.020000,1028.0,1409.0,186,55600.0,89.0,Washington,WA,4708,34-1716542,Ginnie Mae (GNMA),One-to-four family dwelling (other than manufa...,Not applicable,Owner-occupied as a principal dwelling,NaN,FHA-insured,Refinancing,Secured by a first lien,Not a HOEPA loan,NaN,Lewis County,No co-applicant,No co-applicant,No co-applicant,9712.0,2016,0,Male,White,Not Hispanic or Latino,Department of Housing and Urban Development,HUD,Loan originated

In [51]:
# inspect dataset info
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 465951 entries, 0 to 466565
Data columns (total 35 columns):
tract_to_msamd_income             465951 non-null float64
population                        465951 non-null float64
minority_population               465951 non-null float64
number_of_owner_occupied_units    465940 non-null float64
number_of_1_to_4_family_units     465951 non-null float64
loan_amount_000s                  465951 non-null int64
hud_median_family_income          465951 non-null float64
applicant_income_000s             465951 non-null float64
state_name                        465951 non-null object
state_abbr                        465951 non-null object
sequence_number                   465951 non-null int64
respondent_id                     465951 non-null object
purchaser_type_name               465951 non-null object
property_type_name                465951 non-null object
preapproval_name                  465951 non-null object
owner_occupancy_name              465951 non-null object
msamd_name                        428278 non-null object
loan_type_name                    465951 non-null object
loan_purpose_name                 465951 non-null object
lien_status_name                  465951 non-null object
hoepa_status_name                 465951 non-null object
denial_reason_name_1              34348 non-null object
county_name                       465951 non-null object
co_applicant_sex_name             465951 non-null category
co_applicant_race_name_1          465951 non-null object
co_applicant_ethnicity_name       465951 non-null object
census_tract_number               465951 non-null float64
as_of_year                        465951 non-null int64
application_date_indicator        465951 non-null int64
applicant_sex_name                465951 non-null category
applicant_race_name_1             465951 non-null object
applicant_ethnicity_name          465951 non-null object
agency_name                       465951 non-null object
agency_abbr                       465951 non-null object
action_taken_name                 465951 non-null object
dtypes: category(2), float64(8), int64(4), object(21)
memory usage: 121.8+ MB

## Summary of Statistics

In [19]:
#Summary of statistics
WA_HomeLoan_df.describe()

,tract_to_msamd_income,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,sequence_number,census_tract_number,as_of_year,application_date_indicator
count,465951.000000,465951.000000,465951.000000,465940.000000,465951.000000,465951.000000,465951.000000,465951.000000,4.659510e+05,465951.000000,465951.0,465951.000000
mean,106.906157,5288.246378,24.765191,1389.071567,1822.152793,298.122019,76797.282118,109.816970,1.127634e+05,1395.411211,2016.0,0.207472
std,29.280418,1665.317119,15.214418,506.742265,682.014090,759.090489,12959.047619,116.827321,2.021816e+05,2950.871344,0.0,0.609837
min,14.050000,98.000000,2.040000,14.000000,27.000000,1.000000,48700.000000,1.000000,1.000000e+00,1.000000,2016.0,0.000000
25%,87.260002,4124.000000,13.220000,1032.000000,1395.000000,172.000000,65800.000000,64.000000,5.141000e+03,117.010000,2016.0,0.000000
50%,104.529999,5173.000000,20.750000,1359.000000,1734.000000,248.000000,73300.000000,89.000000,2.652600e+04,323.220000,2016.0,0.000000
75%,123.809998,6342.000000,32.220001,1705.000000,2171.000000,350.000000,90300.000000,125.000000,1.097595e+05,702.030000,2016.0,0.000000
max,257.140015,13025.000000,94.790001,2997.000000,5893.000000,99999.000000,90300.000000,9999.000000,1.241780e+06,9757.000000,2016.0,2.000000

In [20]:
sns.boxplot(y=WA_HomeLoan_df.tract_to_msamd_income)
plt.show()

In [24]:
sns.boxplot(y=WA_HomeLoan_df.population)
plt.show()

In [25]:
sns.boxplot(y=WA_HomeLoan_df.minority_population)
plt.show()

In [26]:
sns.boxplot(y=WA_HomeLoan_df.number_of_owner_occupied_units)
plt.show()

In [27]:
sns.boxplot(y=WA_HomeLoan_df.number_of_1_to_4_family_units)
plt.show()

In [29]:
sns.boxplot(y=WA_HomeLoan_df.loan_amount_000s)
plt.show()

In [32]:
sns.boxplot(y=WA_HomeLoan_df.hud_median_family_income)
plt.show()

In [31]:
sns.boxplot(y=WA_HomeLoan_df.applicant_income_000s)
plt.show()

## Outliers

In [21]:
#functions for removing outliers
def removeOutliers(columnName):
    q25 = columnName.quantile(0.25)
    q75 = columnName.quantile(0.75)
    iqr =  q75 - q25
    cutoff = iqr*1.5
    lower = q25 - cutoff
    higher = q75 + cutoff
    columnName.mask(columnName < lower, other = lower, inplace=True)
    columnName.mask(columnName > higher, other = higher, inplace=True)

In [33]:
# Remove outliers
removeOutliers(WA_HomeLoan_df.tract_to_msamd_income)
removeOutliers(WA_HomeLoan_df.population)
removeOutliers(WA_HomeLoan_df.minority_population)
removeOutliers(WA_HomeLoan_df.number_of_owner_occupied_units)
removeOutliers(WA_HomeLoan_df.number_of_1_to_4_family_units)
removeOutliers(WA_HomeLoan_df.loan_amount_000s)
removeOutliers(WA_HomeLoan_df.applicant_income_000s)

In [23]:
sns.boxplot(y=WA_HomeLoan_df.tract_to_msamd_income)
plt.show()

In [34]:
# Summary of statistics
WA_HomeLoan_df.describe()

,tract_to_msamd_income,population,minority_population,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_amount_000s,hud_median_family_income,applicant_income_000s,sequence_number,census_tract_number,as_of_year,application_date_indicator
count,465951.000000,465951.000000,465951.000000,465940.000000,465951.000000,465951.000000,465951.000000,465951.000000,4.659510e+05,465951.000000,465951.0,465951.000000
mean,106.584663,5276.830353,24.366641,1387.772711,1805.411249,270.885112,76797.282118,99.823308,1.127634e+05,1395.411211,2016.0,0.207472
std,28.171963,1629.282971,13.976764,503.024054,618.418129,141.448708,12959.047619,50.860760,2.021816e+05,2950.871344,0.0,0.609837
min,32.435009,797.000000,2.040000,22.500000,231.000000,1.000000,48700.000000,1.000000,1.000000e+00,1.000000,2016.0,0.000000
25%,87.260002,4124.000000,13.220000,1032.000000,1395.000000,172.000000,65800.000000,64.000000,5.141000e+03,117.010000,2016.0,0.000000
50%,104.529999,5173.000000,20.750000,1359.000000,1734.000000,248.000000,73300.000000,89.000000,2.652600e+04,323.220000,2016.0,0.000000
75%,123.809998,6342.000000,32.220001,1705.000000,2171.000000,350.000000,90300.000000,125.000000,1.097595e+05,702.030000,2016.0,0.000000
max,178.634991,9669.000000,60.720003,2714.500000,3335.000000,617.000000,90300.000000,216.500000,1.241780e+06,9757.000000,2016.0,2.000000

## Duplicate Rows

In [20]:
#drop duplicates
WA_HomeLoan_df.drop_duplicates(inplace=True)

In [21]:
WA_HomeLoan_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 466566 entries, 0 to 466565
Data columns (total 37 columns):
tract_to_msamd_income             466566 non-null float64
rate_spread                       466566 non-null float64
population                        466566 non-null float64
minority_population               466566 non-null float64
number_of_owner_occupied_units    466566 non-null float64
number_of_1_to_4_family_units     466566 non-null float64
loan_amount_000s                  466566 non-null int64
hud_median_family_income          466566 non-null float64
applicant_income_000s             466566 non-null float64
state_name                        466566 non-null object
state_abbr                        466566 non-null object
sequence_number                   466566 non-null int32
respondent_id                     466566 non-null object
purchaser_type_name               466566 non-null object
property_type_name                466566 non-null object
preapproval_name                  466566 non-null object
owner_occupancy_name              466566 non-null object
msamd_name                        428292 non-null object
loan_type_name                    466566 non-null object
loan_purpose_name                 466566 non-null object
lien_status_name                  466566 non-null object
hoepa_status_name                 466566 non-null object
edit_status_name                  74505 non-null object
denial_reason_name_1              34499 non-null object
county_name                       466199 non-null object
co_applicant_sex_name             466566 non-null category
co_applicant_race_name_1          466566 non-null object
co_applicant_ethnicity_name       466566 non-null object
census_tract_number               465960 non-null float64
as_of_year                        466566 non-null float64
application_date_indicator        466566 non-null int32
applicant_sex_name                466566 non-null category
applicant_race_name_1             466566 non-null object
applicant_ethnicity_name          466566 non-null object
agency_name                       466566 non-null object
agency_abbr                       466566 non-null object
action_taken_name                 466566 non-null object
dtypes: category(2), float64(10), int32(2), int64(1), object(22)
memory usage: 125.5+ MB

In [22]:
WA_HomeLoan_df.boxplot(column='applicant_income_000s', by='loan_amount_000s')
plt.show()

In [23]:
WA_HomeLoan_df.boxplot()
plt.show()