# **Json Assignment**
**Dataset** is avaliable at:
http://jsonstudio.com/resources/

Using dataset 'world_bank_projects.json':
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [1]:
#import library
import pandas as pd
import json
from pandas.io.json import json_normalize
import numpy as np

In [2]:
#Read Dataset into a frame and inspect first 5 rows
file_name = "E:/Data Science/SpringBoard DS/Data Wrangling Project/Json Project/data_wrangling_json/data_wrangling_json/data/world_bank_projects.json"
df = pd.read_json(file_name)
df.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{u'$oid': u'52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{u'Percent': 46, u'Name': u'Regional integrati...","[{u'code': u'47', u'name': u'Regional integrat...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{u'$oid': u'52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{u'Percent': 50, u'Name': u'Participation and ...","[{u'code': u'57', u'name': u'Participation and...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{u'$oid': u'52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Export development...","[{u'code': u'45', u'name': u'Export developmen...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [3]:
#inspect all the columns
pd.set_option('display.max_columns', 50)
df.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,docty,envassesmentcategorycode,grantamt,ibrdcommamt,id,idacommamt,impagency,lendinginstr,lendinginstrtype,lendprojectcost,majorsector_percent,mjsector_namecode,mjtheme,mjtheme_namecode,mjthemecode,prodline,prodlinetext,productlinetype,project_abstract,project_name,projectdocs,projectfinancialtype,projectstatusdisplay,regionname,sector,sector1,sector2,sector3,sector4,sector_namecode,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,"Project Information Document,Indigenous People...",C,0,0,P129828,130000000,MINISTRY OF EDUCATION,Investment Project Financing,IN,550000000,"[{u'Percent': 46, u'Name': u'Education'}, {u'P...","[{u'code': u'EX', u'name': u'Education'}, {u'c...",[Human development],"[{u'code': u'8', u'name': u'Human development'...","8,11",PE,IBRD/IDA,L,{u'cdata': u'The development objective of the ...,Ethiopia General Education Quality Improvement...,"[{u'DocDate': u'28-AUG-2013', u'EntityID': u'0...",IDA,Active,Africa,"[{u'Name': u'Primary education'}, {u'Name': u'...","{u'Percent': 46, u'Name': u'Primary education'}","{u'Percent': 26, u'Name': u'Secondary education'}","{u'Percent': 16, u'Name': u'Public administrat...","{u'Percent': 12, u'Name': u'Tertiary education'}","[{u'code': u'EP', u'name': u'Primary education...","ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,"Project Information Document,Integrated Safegu...",C,4700000,0,P144674,0,MINISTRY OF FINANCE,Specific Investment Loan,IN,5700000,"[{u'Percent': 70, u'Name': u'Public Administra...","[{u'code': u'BX', u'name': u'Public Administra...","[Economic management, Social protection and ri...","[{u'code': u'1', u'name': u'Economic managemen...","1,6",RE,Recipient Executed Activities,L,NaN,TN: DTF Social Protection Reforms Support,"[{u'DocDate': u'29-MAR-2013', u'EntityID': u'0...",OTHER,Active,Middle East and North Africa,[{u'Name': u'Public administration- Other soci...,"{u'Percent': 70, u'Name': u'Public administrat...","{u'Percent': 30, u'Name': u'General public adm...",NaN,NaN,"[{u'code': u'BS', u'name': u'Public administra...","BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{u'$oid': u'52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,"Resettlement Plan,Environmental Assessment,Int...",B,0,0,P145310,6060000,MINISTRY OF TRANSPORT AND COMMUNICATIONS,Investment Project Financing,IN,6060000,"[{u'Percent': 100, u'Name': u'Transportation'}]","[{u'code': u'TX', u'name': u'Transportation'}]","[Trade and integration, Public sector governan...","[{u'code': u'5', u'name': u'Trade and integrat...","5,2,11,6",PE,IBRD/IDA,L,NaN,Tuvalu Aviation Investment Project - Additiona...,"[{u'DocDate': u'21-OCT-2013', u'EntityID': u'0...",IDA,Active,East Asia and Pacific,[{u'Name': u'Rural and Inter-Urban Roads and H...,"{u'Percent': 100, u'Name': u'Rural and Inter-U...",NaN,NaN,NaN,"[{u'code': u'TI', u'name': u'Rural and Inter-U...",TI,IBRD,Active,Y,"{u'Percent': 46, u'Name': u'Regional integrati...","[{u'code': u'47', u'name': u'Regional integrat...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{u'$oid': u'52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of","Procurement Plan,Project Information Document,...",C,1500000,0,P144665,0,LABOR INTENSIVE PUBLIC WORKS PROJECT PMU,Technical Assistance Loan,IN,1500000,"[{u'Percent': 100, u'Name': u'Health and other...","[{u'code': u'JX', u'name': u'Health and other ...","[Social dev/gender/inclusion, Social dev/gende...","[{u'code': u'7', u'name': u'Social dev/gender/...","7,7",RE,Recipient Executed Activities,L,NaN,Gov't and Civil Society Organization Partnership,"[{u'DocDate': u'15-MAY-2013', u'EntityID': u'0...",OTHER,Active,Middle East and North Africa,[{u'Name': u'Other social services'}],"{u'Percent': 100, u'Name': u'Other social serv...",NaN,NaN,NaN,"[{u'code': u'JB', u'name': u'Other social serv...",JB,IBRD,Active,N,"{u'Percent': 50, u'Name': u'Participation and ...","[{u'code': u'57', u'name': u'Participation and...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{u'$oid': u'52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,"Project Information Document,Integrated Safegu...",B,0,0,P144933,13100000,MINISTRY OF TRADE AND INDUSTRY,Investment Project Financing,IN,15000000,"[{u'Percent': 50, u'Name': u'Industry and trad...","[{u'code': u'YX', u'name': u'Industry and trad...","[Trade and integration, Financial and private ...","[{u'code': u'5', u'name': u'Trade and integrat...","5,4",PE,IBRD/IDA,L,{u'cdata': u'The development objective of the ...,Second Private Sector Competitiveness and Econ...,"[{u'DocDate': u'06-SEP-2013', u'EntityID': u'0...",IDA,Active,Africa,[{u'Name': u'General industry and trade sector...,"{u'Percent': 50, u'Name': u'General industry a...","{u'Percent': 40, u'Name': u'Other industry'}","{u'Percent': 10, u'Name': u'SME Finance'}",NaN,"[{u'code': u'YZ', u'name': u'General industry ...","FH,YW,YZ",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Export development...","[{u'code': u'45', u'name': u'Export developmen...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [4]:
#inspect the Dataframe any missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 50 columns):
_id                         500 non-null object
approvalfy                  500 non-null int64
board_approval_month        500 non-null object
boardapprovaldate           500 non-null object
borrower                    485 non-null object
closingdate                 370 non-null object
country_namecode            500 non-null object
countrycode                 500 non-null object
countryname                 500 non-null object
countryshortname            500 non-null object
docty                       446 non-null object
envassesmentcategorycode    430 non-null object
grantamt                    500 non-null int64
ibrdcommamt                 500 non-null int64
id                          500 non-null object
idacommamt                  500 non-null int64
impagency                   472 non-null object
lendinginstr                495 non-null object
lendinginstrtype            495 non-null object
lendprojectcost             500 non-null int64
majorsector_percent         500 non-null object
mjsector_namecode           500 non-null object
mjtheme                     491 non-null object
mjtheme_namecode            500 non-null object
mjthemecode                 500 non-null object
prodline                    500 non-null object
prodlinetext                500 non-null object
productlinetype             500 non-null object
project_abstract            362 non-null object
project_name                500 non-null object
projectdocs                 446 non-null object
projectfinancialtype        500 non-null object
projectstatusdisplay        500 non-null object
regionname                  500 non-null object
sector                      500 non-null object
sector1                     500 non-null object
sector2                     380 non-null object
sector3                     265 non-null object
sector4                     174 non-null object
sector_namecode             500 non-null object
sectorcode                  500 non-null object
source                      500 non-null object
status                      500 non-null object
supplementprojectflg        498 non-null object
theme1                      500 non-null object
theme_namecode              491 non-null object
themecode                   491 non-null object
totalamt                    500 non-null int64
totalcommamt                500 non-null int64
url                         500 non-null object
dtypes: int64(7), object(43)
memory usage: 195.4+ KB

## 1. Top 10 Countries with Most Projects

In [5]:
# Store top 10 countries with most project to 'top_10_countries'
top_10_countries = df.countryname.value_counts().head(10)
top_10_countries

People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Kingdom of Morocco                 12
People's Republic of Bangladesh    12
Nepal                              12
Republic of Mozambique             11
Africa                             11
Name: countryname, dtype: int64

## 2. Find the top 10 major Project Themes

In [6]:
#Load dataset and inspect the data
with open(file_name, 'r') as json_file:
    json_data = json.load(json_file)

print(json_data[0])

{u'sector': [{u'Name': u'Primary education'}, {u'Name': u'Secondary education'}, {u'Name': u'Public administration- Other social services'}, {u'Name': u'Tertiary education'}], u'supplementprojectflg': u'N', u'projectfinancialtype': u'IDA', u'prodline': u'PE', u'mjtheme': [u'Human development'], u'idacommamt': 130000000, u'impagency': u'MINISTRY OF EDUCATION', u'country_namecode': u'Federal Democratic Republic of Ethiopia!$!ET', u'mjthemecode': u'8,11', u'closingdate': u'2018-07-07T00:00:00Z', u'totalcommamt': 130000000, u'id': u'P129828', u'mjsector_namecode': [{u'code': u'EX', u'name': u'Education'}, {u'code': u'EX', u'name': u'Education'}, {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'}, {u'code': u'EX', u'name': u'Education'}], u'docty': u'Project Information Document,Indigenous Peoples Plan,Project Information Document', u'sector1': {u'Percent': 46, u'Name': u'Primary education'}, u'lendinginstr': u'Investment Project Financing', u'countrycode': u'ET', u'sector2': {u'Percent': 26, u'Name': u'Secondary education'}, u'totalamt': 130000000, u'mjtheme_namecode': [{u'code': u'8', u'name': u'Human development'}, {u'code': u'11', u'name': u''}], u'envassesmentcategorycode': u'C', u'boardapprovaldate': u'2013-11-12T00:00:00Z', u'countryshortname': u'Ethiopia', u'source': u'IBRD', u'prodlinetext': u'IBRD/IDA', u'productlinetype': u'L', u'regionname': u'Africa', u'status': u'Active', u'project_name': u'Ethiopia General Education Quality Improvement Project II', u'sector4': {u'Percent': 12, u'Name': u'Tertiary education'}, u'approvalfy': 1999, u'project_abstract': {u'cdata': u'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'}, u'projectdocs': [{u'DocDate': u'28-AUG-2013', u'EntityID': u'090224b081e545fb_1_0', u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0', u'DocType': u'PID', u'DocTypeDesc': u'Project Information Document (PID),  Vol.'}, {u'DocDate': u'01-JUL-2013', u'EntityID': u'000442464_20130920111729', u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729', u'DocType': u'IP', u'DocTypeDesc': u'Indigenous Peoples Plan (IP),  Vol.1 of 1'}, {u'DocDate': u'22-NOV-2012', u'EntityID': u'090224b0817b19e2_1_0', u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0', u'DocType': u'PID', u'DocTypeDesc': u'Project Information Document (PID),  Vol.'}], u'lendprojectcost': 550000000, u'lendinginstrtype': u'IN', u'theme1': {u'Percent': 100, u'Name': u'Education for all'}, u'grantamt': 0, u'themecode': u'65', u'borrower': u'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA', u'sectorcode': u'ET,BS,ES,EP', u'sector3': {u'Percent': 16, u'Name': u'Public administration- Other social services'}, u'majorsector_percent': [{u'Percent': 46, u'Name': u'Education'}, {u'Percent': 26, u'Name': u'Education'}, {u'Percent': 16, u'Name': u'Public Administration, Law, and Justice'}, {u'Percent': 12, u'Name': u'Education'}], u'board_approval_month': u'November', u'theme_namecode': [{u'code': u'65', u'name': u'Education for all'}], u'countryname': u'Federal Democratic Republic of Ethiopia', u'url': u'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en', u'projectstatusdisplay': u'Active', u'ibrdcommamt': 0, u'sector_namecode': [{u'code': u'EP', u'name': u'Primary education'}, {u'code': u'ES', u'name': u'Secondary education'}, {u'code': u'BS', u'name': u'Public administration- Other social services'}, {u'code': u'ET', u'name': u'Tertiary education'}], u'_id': {u'$oid': u'52b213b38594d8a2be17c780'}}

In [7]:
#data is nested, flatten the data using column mjtheme_namecode and inspect dataframe
df_json = json_normalize(json_data, 'mjtheme_namecode')
df_json.head()

  code                                   name
0    8                      Human development
1   11
2    1                    Economic management
3    6  Social protection and risk management
4    5                  Trade and integration

In [8]:
# Top 10 Themes with missing value
top_10_themes = df_json.name.value_counts().head(10)
top_10_themes

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

## 3.  Create a dataframe with the missing names filled in for column 'mjtheme_namecode'

In [9]:
#Sort and replace with NaN
df_json_sorted=df_json.sort_values(by=['code', 'name'])
bool_data = df_json_sorted['name'] == ''
df_json_sorted['name'][bool_data] = np.nan

In [10]:
#inspect first 15 rows to verify NaN values
df_json_sorted.head(15)

     code                 name
212     1                  NaN
363     1                  NaN
1024    1                  NaN
1114    1                  NaN
1437    1                  NaN
2       1  Economic management
88      1  Economic management
175     1  Economic management
204     1  Economic management
205     1  Economic management
220     1  Economic management
222     1  Economic management
223     1  Economic management
249     1  Economic management
357     1  Economic management

In [11]:
#back fill the sorted Dataframe and store in into 'df_filledIn'
df_filledIn = df_json_sorted.fillna(method = 'bfill')
#inspect 'df_filledIn'
df_filledIn.head(15)

     code                 name
212     1  Economic management
363     1  Economic management
1024    1  Economic management
1114    1  Economic management
1437    1  Economic management
2       1  Economic management
88      1  Economic management
175     1  Economic management
204     1  Economic management
205     1  Economic management
220     1  Economic management
222     1  Economic management
223     1  Economic management
249     1  Economic management
357     1  Economic management

## Top 10 Themes after filling Missing values

In [12]:
# Top 10 themes after filling the missed in values
df_filledIn.name.value_counts().head(10)

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Name: name, dtype: int64